apiVersion: v1
kind: Pod
metadata:
  name: static-site
  labels:
    web: static-site
spec:
 containers:
 - name: static-site
   image: ajaypb1122/static-site:v1
   ports:
    - containerPort: 80