apiVersion: v1
kind: Service
metadata:
  name: node-app-svc-dev

spec:
  type: NodePort
  ports:
    - port: 300
      nodePort: 32001
      protocol: TCP

  selector:
    environment: dev

