apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
  labels:
    app: web
spec:
  replicas: 2
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # it defines how many pods can be unavailable during the rolling update
      maxSurge: 1 # how many pods we can add at a time
  selector:
    matchLabels: 
      component: static-site
  template:
    metadata:
      labels:
        component: static-site
      
    spec:
      containers:
        - name: static-site-pod
          image: ajaypb1122/static-site:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-gen-svc
spec:
  selector:
    app: web
  type: NodePort 
  ports:
  - name: web-port
    port:  80
    nodePort: 30080
    protocol: TCP