apiVersion: v1
kind: Pod
metadata:
  name: mysql-vol

spec:
  containers:
  - image:  mysql:5.7
    name:  mysql-pod
    ports:
    - name: db-port
      containerPort: 3306
    volumeMounts:
    - name:  mydb-mount
      mountPath:  "/var/db/mysql/"
    env:
      - name:  wp-sec
        value:  db-password
  volumes:
  - name:  mydb-mount
    persistentVolumeClaim:
      claimName: myclaim-1 
