apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customRole

rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]


- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]


- apiGroups: ["storage.k8s.io/v1"]
  resources: ["provisioner"]
  verbs: ["get","list"]