apiVersion: v1
kind: Service
metadata:
  name: static-user-site-ip-service
  labels: 
    web: static-site-user
  namespace: userdefinedspace

spec:
  type: NodePort
  selector: 
    component: static-site-user

  ports:
  - port: 80
    nodePort: 30001