apiVersion: v1
kind: Pod
metadata:
  name: conf-pod-env
  
spec:
  containers:
  - name: conf-pod-env
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "env" ]
    env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: log_level
  restartPolicy: Never