apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey

data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICJZV3BoZVRJMU16VXhOenBXZVc5dFFEVXpOVEUzIgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy40IChsaW51eCkiCgl9Cn0=
type: kubernetes.io/dockerconfigjson