apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-demo

spec:
  replicas: 3
  selector:
    app: node-app
  template:
    metadata:
      labels: 
        app: node-app
    spec:
      containers:
      - name: node-app-rc
        image: ajaypb1122/node-app-prod:v1
        ports:
        - name: nodejs-port
          containerPort: 3000