apiVersion: v1
kind: Pod
metadata: 
  name: py-pod
  labels:
    app: web
spec:
  containers:
    - image: ajaypb1122/py-gen:v1
      name: pycon 
      ports:
      - containerPort: 5000
      resources:
       requests:
        memory: "64Mi"
        cpu: "250m"
       limits: 
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: py-lb
spec:
  selector:
    app: web
  type:  LoadBalancer 
  ports:
  - name: web-port
    port:  80
    targetPort:  8080
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127