apiVersion: v1
kind: Pod
metadata: 
  name: py-pod
  labels:
    app: web
spec:
  containers:
    - image: ajaypb1122/py-gen:v1
      name: pycon 
      ports:
      - containerPort: 5000
      resources:
       requests:
        memory: "64Mi"
        cpu: "250m"
       limits: 
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: py-cluster-svc
spec:
  selector:
    app: web
  type: ClusterIP 
  ports:
  - name: app-port
    port:  5000
    targetPort: 5000