apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-restart-1

spec:
  containers:
  - name: pod-on-failure
    image: gcr.io/google-samples/hello-app:1.0 
  restartPolicy: OnFailure 


---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-restart-2

spec:
  containers:
  - name: pod-on-never
    image: gcr.io/google-samples/hello-app:1.0 
  restartPolicy: Never 
