apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata: 
  name: common-properties
spec:
  selector: 
    matchLabels:
      app: myapp
  env:
    - name: MY_SECRET
      value: "123456" 

  volumeMounts:
    - name: shared-mount
      mountPath: /shared-drive
  
  volumes:
    - name: shared-mount
      emptyDir: {}
    