apiVersion: apps/v1
kind: Deployment
metadata:
  name: preset-dep
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: ajaypb1122/node-app-prod:latest
        name:  node-app

---
apiVersion: v1
kind: Pod
metadata:
  name: onlypod
  labels:
    app: myapp

spec:
  containers:
  - name: static-site
    image: ajaypb1122/static-site      


    