apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpademo
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: webapp
  
  template:
    metadata:
      labels:
        app: webapp  
    spec:
      containers:
      - name: hpa-app
        image: k8s.gcr.io/hpa-example
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests: 
            cpu: 200m 

---
apiVersion: v1
kind: Service
metadata:
  name: hpa-svc
  
spec:
  type: NodePort 
  ports:
    - port: 80
      nodePort: 30080
      protocol: TCP
  selector:
    app: webapp 