apiVersion: v1
kind: Pod
metadata:
  name: node-app-helloworld-dev
  labels:
    app: node-app

  
spec:
  containers:
    - name: node-app
      image: ajaypb1122/node-app-prod:latest
      ports:
        - containerPort: 3000
