apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-rolling-v2
spec:
  replicas: 3
  selector:
    goapp: k8s-rc-demo
    version: v0.2
  template:
    metadata:
      labels:
        goapp: k8s-rc-demo
        version: v0.2
    spec:
      containers:
        - name: k8s-deployment-demo
          image: ryane/k8s-deployment-demo:0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: DEMO_ENV
              value: prod