apiVersion: v1
kind: Pod
metadata: 
  name: static-site
  labels:
    dc: prod
    version: v1

spec:
  containers:
  - name: my-static-site
    image: ajaypb1122/static-site:latest
    ports:
    - containerPort: 80
