apiVersion: v1
kind: Service
metadata: 
  name: static-site-rc-service
  labels: 
    web: static-site
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001
      protocol: TCP

  selector:
    web: static-site
