apiVersion: v1
kind: ReplicationController
metadata: 
  name: static-site-rc
spec:
  replicas: 5
  selector: 
    web: static-site
  template:
    metadata: 
      labels:
        web: static-site
    spec:
      containers:
      - name: my-static-site
        image: ajaypb1122/static-site:latest
        ports:
          - containerPort: 80
