apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-secerts
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: app-secert
  template:
    metadata:
      labels:
        app: app-secert
    spec:
      containers:
      - name: deploy-secert
        image: ajaypb1122/node-app-prod:latest
        ports:
        - name: app-port
          containerPort: 3000
        volumeMounts:
        - name: cred-volume
          mountPath: /etc/creds
          readOnly: true
      volumes:
      - name: cred-volume
        secret:
          secretName: db-user-pass
    