apiVersion: v1
kind: Pod
metadata:
  name: exec-pod
spec:
  containers:
  - name: exec-pod
    image: alpine:3.10
    imagePullPolicy: Always
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy ; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 10
      periodSeconds: 20