apiVersion: v1
kind: Pod
metadata:
  name: probe-pod
spec:
  containers:
  - image: ajaypb1122/py-gen:v1
    name: pod-cont  
    ports:
    - containerPort: 5000
    readinessProbe:
      tcpSocket:
        port: 5000
      initialDelaySeconds: 10
      periodSeconds: 20
    livenessProbe:
      tcpSocket:
        port: 5000
      initialDelaySeconds: 30
      periodSeconds: 10