apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    web: static-site
spec:
 containers:
 - name: static-site
   image: ajaypb1122/static-site:latest
   ports:
    - containerPort: 80
   resources:
     requests:
       memory: "64Mi"
       cpu: "250m"
     limits: 
       memory: "128Mi"
       cpu: "500m"