apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod-ssd
spec:
  containers:
  - name: nginx-pod1
    image: nginx
    ports:
    - containerPort: 80
  nodeSelector:
    disk: local_ssd

---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod-gpu
spec:
  containers:
  - name: nginx-pod2
    image: nginx
    ports:
    - containerPort: 80
  nodeSelector:
    hardware: local_gpu

---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
spec:
  containers:
  - name: nginx-pod3
    image: nginx
    ports:
    - containerPort: 80


