apiVersion: v1
kind: Pod
metadata: 
  name: pod1withlabel-1
  labels:
    app: MyWebApp
    deployment: v1
    tier: prod
spec:
  containers:
  - name: nginx-pod1
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata: 
  name: podwithlabel-2
  labels:
    app: MyWebApp
    deployment: v1.1
    tier: prod
spec:
  containers:
  - name: nginx-pod2
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata: 
  name: podwithlabel-3
  labels:
    app: MyWebApp
    deployment: v1.1
    tier: qa
spec:
  containers:
  - name: nginx-pod3
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata: 
  name: pod1withlabel-4
  labels:
    app: MyAdminApp
    deployment: v1
    tier: prod
spec:
  containers:
  - name: nginx-pod4
    image: nginx
    ports:
    - containerPort: 80
